spring.application.name=reservas

#Configuración de MySQL
spring.datasource.url=jdbc:mariadb://192.168.56.102:3306/reservas-bosco
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

#Para ver las SQL que se ejecutan
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
